name: Lint & Build
run-name: Lint & Build

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: true
        type: string

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (Latest)
        uses: actions/setup-node@v4
        with:
          node-version: "22.4.1"

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

  build:
    needs: lint
    name: Run Build Process
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build --if-present

      - name: Verify SSR Compatibility (for Node.js 19+)
        if: startsWith(matrix.node-version, '19') || startsWith(matrix.node-version, '20') || startsWith(matrix.node-version, '21') || startsWith(matrix.node-version, '22')
        run: npm run validate:ssr

  trigger-tests:
    needs: build
    name: "Run Tests"
    uses: ./.github/workflows/test.yml
    with:
      node-version: "22.4.1"
